version: '3.8'

services:

  normal:
    image: eclipse-temurin:26-jdk
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "javac -encoding UTF-8 -d bin src/capitulo1/PesquisaBinariaNumeros.java && java -cp bin capitulo1.PesquisaBinariaNumeros"

  debug:
    image: eclipse-temurin:26-jdk
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5005:5005"
    command: sh -c "javac -g -encoding UTF-8 -d bin src/capitulo1/PesquisaBinariaNumeros.java && java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005 -cp bin capitulo1.PesquisaBinariaNumeros"